### ISSUE TITLE
e2e: designer/routeBeanConf.cy.ts fails sporadically on firefox

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#603]
### Describe the Bug

It fails sporadically on PR check, usually it passes by re-running it once or twice. I haven't yet reproduced it locally. 
e.g.
https://github.com/KaotoIO/kaoto-next/actions/runs/7452534410/job/20276847563#step:7:8694

```
  Test for node bean reference and configuration support
    1) Beans - create a new bean in route using bean editor
    ✓ Beans - select existing bean in node form config (2964ms)
    ✓ Beans - unselect selected bean (3560ms)
    - Beans - delete bean using the bean editor


  2 passing (18s)
  1 pending
  1 failing

  1) Test for node bean reference and configuration support
       Beans - create a new bean in route using bean editor:
     CypressError: Timed out retrying after 8050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:

> <div.pf-v5-c-form__group>

We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page. Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You can typically solve this by breaking up a chain. For example, rewrite:

> `cy.get('button').click().click()`

to

> `cy.get('button').as('btn').click()`
> `cy.get('@btn').click()`
https://on.cypress.io/element-has-detached-from-dom
  at retryActionability (http://localhost:4173/__cypress/runner/cypress_runner.js:112274:74)
  at tryCatcher (http://localhost:4173/__cypress/runner/cypress_runner.js:1807:23)
  at __webpack_modules__</module.exports/Promise.try (http://localhost:4173/__cypress/runner/cypress_runner.js:4315:29)
  at whenStable (http://localhost:4173/__cypress/runner/cypress_runner.js:144073:62)
  at __webpack_modules__</create/retry (http://localhost:4173/__cypress/runner/cypress_runner.js:144014:14)
  at tryCatcher (http://localhost:4173/__cypress/runner/cypress_runner.js:1807:23)
  at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:4173/__cypress/runner/cypress_runner.js:1519:31)
  at __webpack_modules__</module.exports/Promise.prototype._settlePromise (http://localhost:4173/__cypress/runner/cypress_runner.js:1576:18)
  at __webpack_modules__</module.exports/Promise.prototype._settlePromise0 (http://localhost:4173/__cypress/runner/cypress_runner.js:1621:10)
  at __webpack_modules__</module.exports/Promise.prototype._settlePromises (http://localhost:4173/__cypress/runner/cypress_runner.js:1701:18)
  at __webpack_modules__</module.exports/Promise.prototype._fulfill (http://localhost:4173/__cypress/runner/cypress_runner.js:1645:18)
  at __webpack_modules__</module.exports/Promise.delay/handle< (http://localhost:4173/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at shouldFn (http://localhost:4173/__cypress/runner/cypress_runner.js:117699:18)
      at should (http://localhost:4173/__cypress/runner/cypress_runner.js:117813:23)
      at __webpack_modules__</create/injectAssertion (http://localhost:4173/__cypress/runner/cypress_runner.js:143348:39)
      at assertions (http://localhost:4173/__cypress/runner/cypress_runner.js:143597:16)
      at tryCatcher (http://localhost:4173/__cypress/runner/cypress_runner.js:1807:23)
      at gotValue (http://localhost:4173/__cypress/runner/cypress_runner.js:6478:18)
      at gotAccum (http://localhost:4173/__cypress/runner/cypress_runner.js:6465:25)
      at tryCatcher (http://localhost:4173/__cypress/runner/cypress_runner.js:1807:23)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:4173/__cypress/runner/cypress_runner.js:1519:31)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromise (http://localhost:4173/__cypress/runner/cypress_runner.js:1576:18)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromiseCtx (http://localhost:4173/__cypress/runner/cypress_runner.js:1613:10)
      at _drainQueueStep (http://localhost:4173/__cypress/runner/cypress_runner.js:2411:12)
      at _drainQueue (http://localhost:4173/__cypress/runner/cypress_runner.js:2400:24)
      at __webpack_modules__</Async.prototype._drainQueues (http://localhost:4173/__cypress/runner/cypress_runner.js:2416:16)
      at __webpack_modules__</Async/this.drainQueues (http://localhost:4173/__cypress/runner/cypress_runner.js:2286:14)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     17 seconds                                                                       │
  │ Spec Ran:     designer/routeBeanConf.cy.ts                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Steps to Reproduce the Bug or Issue

1. Create a PR
2. Cross your fingers
3. If it doesn't fail, re-run the job again

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by tplevko** [comment]
thanks @igarashitm, I haven't noticed this. Will try to improve the stability, so there are no false positives

**Comment by tplevko** [comment]
https://github.com/KaotoIO/kaoto-next/pull/604 was merged, closing this issue
