### ISSUE TITLE
Error when saving bean `camelResource?.createBeansEntity is not a function`

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#642]
### Describe the Bug

```
Uncaught TypeError: camelResource?.createBeansEntity is not a function
    at Object.onCreateBean (BeanReferenceField.tsx:220:61)
    at NewBeanModal.tsx:30:11
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
```

### Steps to Reproduce the Bug or Issue

1. create a kamelet
2. select the https element
3. go to `Ssl Context parameters`, clcik on dropdown, select "create new bean"
4. provide values in modal
5. click `Create`
--> nothing is happenign in UI and there is a stack in console log

### Screenshots or Videos

![cannotCreatenewBean](https://github.com/KaotoIO/kaoto-next/assets/1105127/062f8212-5d92-4d57-8e6b-3bde6eb85080)

### Platform

online kaoto version

**Comment by igarashitm** [comment]
kamelet bean is not yet supported - https://github.com/KaotoIO/kaoto-next/issues/540
