### ISSUE TITLE
Port Bean configuration UI

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#8]
### Please describe the feature that you want to propose

Port Bean configuration UI (MetadataEditor component) from kaoto-ui.

**Comment by igarashitm** [comment]
I started from copying files from kaoto-ui and hit an import error on uniforms .js file
```
"default" is not exported by "../uniforms-patternfly/dist/cjs/wrapField.js", imported by "src/components/MetadataEditor/PropertiesField.tsx".
file: /home/toigaras/workspace/Kaoto/kaoto-next/packages/ui/src/components/MetadataEditor/PropertiesField.tsx:3:7
1: import { AddPropertyButtons } from './AddPropertyButtons';
2: import { PropertyRow } from './PropertyRow';
3: import wrapField from '@kaoto-next/uniforms-patternfly/dist/cjs/wrapField';
          ^
4: import { EmptyState, EmptyStateBody, Stack, StackItem } from '@patternfly/react-core';
5: import {
error during build:
RollupError: "default" is not exported by "../uniforms-patternfly/dist/cjs/wrapField.js", imported by "src/components/MetadataEditor/PropertiesField.tsx".
    at error (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:13716:16)
    at Module.traceVariable (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:14146:29)
    at ModuleScope.findVariable (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:12589:39)
    at FunctionScope.findVariable (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:8309:40)
    at CallExpression.bind (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:9875:15)
    at ReturnStatement.bind (file:///home/toigaras/workspace/Kaoto/kaoto-next/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
```

It's here in the code - https://github.com/igarashitm/kaoto-next/commit/d59e459cc005bc50300d004873e296aba5d6e3af#diff-11b0615911fef30b63d0671102541f9c6e13b7d0ff2271e0a04cbe1fef22d80cR3

@lordrip does it ring your bell? it works in kaoto-ui, not sure what's different.

**Comment by igarashitm** [comment]
nevermind, it just needs to use from esm instead.

**Comment by lordrip** [comment]
Did that happened when using `import wrapField from '@kaoto-next/uniforms-patternfly'` directly?

**Comment by lordrip** [comment]
if we need access to `wrapField`, we could add the following line to the `index.ts` file:

```
export { default as wrapField } from "./wrapField";
```
